### ISSUE TITLE
Port not included from ParseServer's serverURL

### ISSUE THREAD

**Issue by mrclay** [parse-community/parse-server-fs-adapter#11]
Our serverURL is `http://localhost:8080/parse` but Parse.File data is sent to the client with `url: "http://localhost/parse/files/..."`. The URLs are otherwise correct, they're just missing the port.

I'm new to Parse so apologies if I'm missing something.

**Comment by flovilmart** [comment]
You should set publicServerURL with a publicly accessible URL

**Comment by mrclay** [comment]
Thank you!
