### ISSUE TITLE
Project isn't linted

### ISSUE THREAD

**Issue by cbaker6** [parse-community/parse-server-fs-adapter#44]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server-fs-adapter/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server-fs-adapter/issues?q=is%3Aissue).

### Current Limitation

The project isn't linted

### Feature / Enhancement Description

Lint the project to make code conform to a standard

### Example Use Case

Similar to parse-server project

### Alternatives / Workarounds

Use as is.

### 3rd Party References

N/A

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [3.0.0](https://github.com/parse-community/parse-server-fs-adapter/releases/tag/3.0.0)
