### ISSUE TITLE
semantic-release 21.0.1 not compatible with current packages

### ISSUE THREAD

**Issue by cbaker6** [parse-community/parse-server-fs-adapter#45]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server-fs-adapter/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server-push-adapter/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse FS Adapter](https://github.com/parse-community/parse-server-fs-adapter/releases). 

### Issue Description

semantic-release 21.0.1 isn't compatible with current dev dependencies and #41 should be reverted

### Steps to reproduce

Run a PR with the current CI

### Actual Outcome

CI currently isn't passing: https://github.com/parse-community/parse-server-fs-adapter/actions/runs/4840918230/jobs/8626857506

For reference, the parse-server is still on the older version: https://github.com/parse-community/parse-server/blob/9674d4a2c0a9d0cda112056a6a2b1629931f37a3/package.json#L107

### Expected Outcome

CI should pass successfully 

###  Environment

Client
- Parse Server Push Adapter version: `2.0.0`

Server
- Parse Server version: `6.0.0`
- Operating system: `Linux`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Local (docker)`

Database
- System (MongoDB or Postgres): `Postgres`
- Database version: `15`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `Local (docker)`

**Comment by mtrezza** [comment]
> semantic-release 21.0.1 isn't compatible with current dev dependencies and https://github.com/parse-community/parse-server-fs-adapter/pull/41 should be reverted

Closing; issue seems based on an incorrect conclusion; see https://github.com/parse-community/parse-server-fs-adapter/issues/47.
