### ISSUE TITLE
Release workflow not working

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server-fs-adapter#47]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server-fs-adapter/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server-push-adapter/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse FS Adapter](https://github.com/parse-community/parse-server-fs-adapter/releases). 

### Issue Description

Release workflow not working

### Steps to reproduce

https://github.com/parse-community/parse-server-fs-adapter/actions/runs/4840918230

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [2.0.1](https://github.com/parse-community/parse-server-fs-adapter/releases/tag/2.0.1)
